### ISSUE TITLE
Build is resolving to wrong @angular/core component

### ISSUE THREAD

**Issue by dfbaskin** [dfbaskin/lerna-angular-cli-monorepo#1]
When building the main web application (after building the libraries for the "three" and "four" examples), the build fails with the following error:

```
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported.
Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file),
resolving symbol NgModule in /home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/demo-app-example-three/node_modules/@angular/core/core.d.ts, resolving symbol ExampleThreeModule in /home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/demo-app-example-three/dist/demo-app-example-three.d.ts, resolving symbol ExampleThreeModule in /home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/demo-app-example-three/dist/demo-app-example-three.d.ts
    at positionalError (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler/bundles/compiler.umd.js:25266:35)
    at simplifyInContext (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler/bundles/compiler.umd.js:25109:27)
    at StaticReflector.simplify (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler/bundles/compiler.umd.js:25123:13)
    at StaticReflector.annotations (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler/bundles/compiler.umd.js:24553:41)
    at _getNgModuleMetadata (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/dfbaskin/dev/lerna-angular-cli-monorepo/packages/demo-app-main/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

The error indicates that the compiler is picking up the `@angular/core` component from the "three" example rather than using the one from the main project (which I believe leads to duplicate instances of core definitions).

To work around the issue, you must remove the `@angular/core` directory from the `node_modules` path in the "three" example.

**Comment by dfbaskin** [comment]
Changed the implementation so that it moves the output of `packagr` to a `libs` folder within the main project (within the `src` directory).  This fixes the build errors, but it seems like there should be a way to build without having to doing this.
